### ISSUE TITLE
Hifiasm and simplex nanopore data

### ISSUE THREAD

**Issue by diego-rt** [chhylp123/hifiasm#530]
Hello, just a few questions regarding the use of nanopore data with hifiasm.

In the process of generating our Ultra-long Nanopore data we have generated a large volume of Q20+ simplex reads and a relatively minor fraction of duplex reads. 

1. My understanding is that **duplex** reads can be used together with the HiFi reads in hifiasm without major concern? I assume that it does not matter that the duplex reads would be much longer than the HiFi reads since they come from an ultralong library?

2. I was wondering whether you have any experience in terms of using the Q20+ **simplex** nanopore reads together with the HiFi reads? As long as the read quality values are accurate I guess it shouldn't matter whether the reads are simplex or duplex? 

3. I understand it's a bit of an arbitrary threshold, but do you have any recommendations for which should be the quality threshold for the HiFi/Nanopore reads used in the standard hifiasm mode? I assume Q20? Consequently, I assume anything ultra long (50/100 kbp+) but with qualities under Q20 should be used in the ultra long mode (--ul)?

4. If I have a 100 kbp Q20 read, does it make any difference whether I use it in the standard hifiasm mode or in the ultra-long mode?

Thanks a lot for your time and advice!

**Comment by chhylp123** [comment]
1. Yes. Another option is to use it as the UL reads with `--ul`.
2. My experience is that Q20 reads do not work well since they still have concurrent sequencing errors. Thus, hifiasm will regard these concurrent sequencing errors as real variants, making the final assembly fragmented.
3. You can feed Q20 reads in any length with `--ul`. But it would be better to discard too short Q20 reads with `--ul-cut` as they do not make sense in practice. In addition, you could have a try to set much smaller error threshold for Q20 reads with `--ul-rate`.  
4. It would be better to use Q20 reads in the ultra-long mode as they may have concurrent sequencing errors.

**Comment by diego-rt** [comment]
Hi, thanks a lot for your quick reply!

1. Ok.
2. By concurrent errors, you mean regions within the read with numerous consecutive or near consecutive errors? Why wouldn't they be corrected by hifiasm's error correction algorithm? And why doesn't this affect HiFi reads since those are also Q20? Or do you typically filter your HiFi reads to a higher quality threshold? 
3. Is there a quality threshold at which you would feel comfortable using simplex nanopore data (together with a much larger dataset of HiFi data) in the standard mode? Perhaps something like Q23 or Q25? I'm currently filtering my ultra long reads by Q10 and adjusted `--ul-rate` to 0.1, but I didn't quite understand how this threshold is used. Does hifiasm discard reads which align to the graph with a lower identity than this?
4. I guess my concern is that I've noticed that some regions of my assembly graph have a relatively shallow sequencing depth (3-10x) and I assume this is because of some underlying sequencing bias (since my coverage is quite alright at 73x) or high repetitiveness (and therefore reads/kmers getting discarded). I was wondering whether the remaining gaps in my assembly arise from hard to sequence regions and I could counteract this by providing some sequencing coverage with a different technology (i.e. nanopore duplex).  
5. Do you have any experience with hybrid duplex + HiFi assemblies?
6. If these regions fail to assemble because of repetitiveness, what would be the main paramter to adjust? I assume one would have to increase -D way way too high to have an effect on satellite-derived Kmers? Is --max-kocc a better alternative? How high would you go and would it significantly affect runtime? Assembly is already taking 10 days with our genome size (30 Gbp). Happy to wait if it gets us to T2T though!
7. What is the reason for preferring "odd rounds of error correction in practice"? In my experience with Revio Pacbio data, there are very few corrections in the third round and I'm a bit concerned that this last round is then being counterproductive by overhomogenizing lowly sequenced genomic regions?

Thanks a lot for your time and the in-depth discussion!

**Comment by chhylp123** [comment]
2. When doing the error correction, there is no assumption for hifiasm. If a sequencing error appears multiple times, hifiasm will think it is a real SNP. As such the contigs/untigs might be broken out due to this concurrent sequencing error. PacBio HiFi reads have very rare concurrent sequencing errors, while Q20 reads still have some of them (at least based on our observation last year). Hifiasm does not filter out any read in advance.
3. Yes, `--ul-rate 0.1` means the sequence identity of UL reads should be 90%. Unfortunately we haven't done enough test for simplex nanopore data, but I feel like you could have a try with `0.1`, `0.15` or `0.2`?
4. Yes.
5.  We haven't. There is a talk talking about duplex reads: https://www.youtube.com/watch?v=ttoQHrr5ZYE. Please note that at that moment, hifiasm does not support scaffolding. So the N50 of hifiasm assembly is contig N50.
6. All these paramters might be helpful. But I guess adding UL reads will be much more important.
7. We previously found odd rounds of error correction work better for the human genome assembly using early versions of hifiasm. Actually it is hard to say for current version and other species.

**Comment by diego-rt** [comment]
2. Is there a parameter controlling the frequency of mismatches required to call a SNP over a sequencing error? Perhaps raising it from 3 to 4-5 would allow one to use Q20+ nanopore reads more confidently?
3. With Kit 14 chemistry we have observed that most ultra long reads have quality values in the range of Q15-Q22. Would it be beneficial then to increase the `--ul-rate` parameter to 0.05 (Q15) for example? OR do you expect no benefit over setting it to `0.1`? Can you elaborate on how exactly `--ul-rate` is implemented? I assume hifiasm filters ultra long alignments with more mismatches than permitted by `--ul-rate` ?

5. I noticed that the recent hifiasm release mentions scaffolding. Does this mean that HiC scaffolding is now implemented?

8. I've noticed that raising `-k` and `-w` to 63 makes the assembly considerably faster. I assume that this is at the cost of higher memory consumption? Do you have any expectations on how this would affect assembly accuracy at repeats? I imagine it would improve repeat resolution?

Thanks!!

**Comment by chhylp123** [comment]
2. Unfortunately, there is no option for that right now. Simply increase it may collapse reapeats. But we would like to have a try to optimize hifiasm for Q20 later.
3. Yes,  hifiasm filters ultra long alignments with more mismatches than permitted by --ul-rate. Since I do not have enough experience for Kit 14, you may have a try different values for `--ul-rate`.
4. No, this is the dual scaffolding without needing additional data. Essentially, the two haplotypes scaffold each other. The process mirrors two rounds of reference-guide scaffolding: initially, haplotype 1 is scaffolded using haplotype 2 as the reference genome, and then vice versa.
5. It is case-by-case. But I feel like raising `-k` and `-w` to `63` may not take much larger memory.

**Comment by kokyriakidis** [comment]
So, raising `-k` and `-w` to 63 will probably yield better results in complex regions?

**Comment by diego-rt** [comment]
Last question: is the number of reads not considered because of the `--ul-rate` parameter reflected anywhere in the log? Because the log says that basically all the UL reads that I provided are "passed reads", which I find hard to believe considering that I set it to 0.06.

```
M::scall_ul_pipeline::630480.509] ==> Qualification
[M::scall_ul_pipeline::] ==> # reads: 5621009, # bases: 0
[M::scall_ul_pipeline::] ==> # fully covered reads: 5381615
[M::write_all_ul_t] Index has been written.
[M::print_ovlp_src_bl_stat::] ==> # HiFi reads:117442443, # covered HiFi reads:15929511, # chained HiFi reads:15204696
[M::print_ovlp_src_bl_stat::] ==> # passed UL reads:5621009, # fully corrected UL reads:5122174, # almost fully corrected UL reads:188329, # UL reads have primary chains:308569
```

**Comment by chhylp123** [comment]
The `# passed UL reads` indicates how many UL reads hifiasm got. The `# fully corrected UL read`, `# almost fully corrected UL reads`, and `# UL reads have primary chains` are how many good UL reads.

**Comment by diego-rt** [comment]
Perfect, thanks!!
